### ISSUE TITLE
Can I override the color scheme?

### ISSUE THREAD

**Issue by hajiifu** [sssmi/after-dark#12]
Hi, I downloaded the After Dark theme and I really like it, thank you!

But only the type colors when writing in Typescript are not to my liking.
Is it possible to override the type color with another color?

```typescript
type Foo = { a: number; b: number }
const foo = ref<Foo>({ a: 3, b: 3 })
// I want Foo to be a different color than foo.
```

Sorry if this is written somewhere and I missed it.

**Comment by sssmi** [comment]
Hi, awesome to hear you like the theme! 

You can certainly override any color in vscode settings.
Here's an example:
```json
"editor.semanticTokenColorCustomizations": {
  "enabled": true,
  "[After Dark]": {
    "rules": {
      "interface": {
        "foreground": "#f00"
      },
      "type": {
        "foreground": "#f00"
      },
      "enum": "#f00",
    }
  }
},
```
