### ISSUE TITLE
"No Italics" not working

### ISSUE THREAD

**Issue by 2jacobtan** [sssmi/after-dark#13]
Would be nice to have "no italics" working again.

(I've tested other themes' "no italics" version and they work fine.)

Thanks for the beautiful theme.

**Comment by sssmi** [comment]
Hi, thanks feedback.
I just tested italics and "no italics" versions and seems to work fine. Could you post a screenshot of the issue here?

**Comment by 2jacobtan** [comment]
(sorry it's not convenient to take screenshot right now)

I assumed "no italics" version would remove the italics in comments. But comments still appear in italics.

Perhaps this was your intention after all, then it's my fault for making a wrong assumption.

I "fixed" it myself by adding this to my `settings.json`.

```json
    "[After Dark No Italics]": {
      "textMateRules": [
        { "scope": "comment",
          "settings": {
            "fontStyle": ""
          }}]
    }
```
