### ISSUE TITLE
Unnecessary code is not shown in different colour

### ISSUE THREAD

**Issue by tomdl89** [sssmi/after-dark#2]
Not sure if a bug or intentional, but since using After Dark, I've noticed unused code is no longer a different colour. In the vscode dark and light themes, unnecessary code appears with reduced opacity, which makes it easier to spot when an unused function or unused symbol.
I've tried adding `editorUnnecessaryCode.border` and `editorUnnecessaryCode.opacity` to After Dark-color-theme.json but it hasn't made any difference. I know nothing about making themes, but would appreciate an update with Unnecessary Code handling if possible. Thanks!

**Comment by sssmi** [comment]
Hi! Thanks for the feedback and sorry it took so long to address this issue.
This is now fixed. #3
