### ISSUE TITLE
Visual Enhancements Request

### ISSUE THREAD

**Issue by vinaysharma14** [sssmi/after-dark#6]
Firstly, I love using **After Dark** as it's really soothing to eyes. Great work on this theme!  ❤️
I use it on VS Code and feel there are 2 cases where it gets visually difficult to work.

- **Sidebar**
The sidebar is difficult to resize as it takes multiple attempts to place mouse on the invisible border to drag it. I would suggest having a light coloured right border on it to distinguish it from the rest of the editor space.

<img width="1440" alt="sidebar" src="https://user-images.githubusercontent.com/48080660/103202970-e6325380-4919-11eb-9a34-76bf8091e4b8.png">

- **Multiple Cursor Selection**
While using `⌘D` to select all the occurrences of the current selection, it gets difficult to visualise which all occurrences have the cursor. It's because the colour of the blinking cursor blends in with that of highlighted border around the occurrences. In the screenshot below it's difficult to figure out that first 3 occurrences of `console` have cursor unless one increases the font size.

<img width="633" alt="multiple cursor" src="https://user-images.githubusercontent.com/48080660/103203573-3827a900-491b-11eb-87ef-46f43878fced.png">

Let me know if you need any additional information. Thanks!

**Comment by sssmi** [comment]
Hi, thank you. Great that you like it 🙏!
I have now fixed these issues in version 1.4

**Comment by vinaysharma14** [comment]
Wow, it looks absolutely amazing now! Thanks a lot @sssmi ! 🚀

**Comment by vinaysharma14** [comment]
@sssmi can this issue be reopened as these input boxes are difficult to distinguish visually? Having a light coloured border around them would be helpful :)

- Search
- Files to include
- Files to exclude
- Message (⌘Enter to commit on 'xyz')
- Search Extensions in Marketplace

The screenshot below covers first three bullet points whereas rest two can be accessed from the highlighted buttons.

<img width="443" alt="Screenshot 2021-01-20 at 1 05 02 PM" src="https://user-images.githubusercontent.com/48080660/105142252-65cdcf80-5b20-11eb-996a-3d6fc3e5869d.png">

**Comment by sssmi** [comment]
Hi, good idea. I just added background color for input field #7

**Comment by vinaysharma14** [comment]
@sssmi thanks again for your efforts! :)
